### ISSUE TITLE
one.search returns empty when subjects a list

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#156]
**Describe the bug**
It seems the `subjects` param of one.search only works with a single string, not a list of strings as the documentation indicates.  If it is assumed that every session is associated with one subject then the query should be doing a logical OR operation.  Perhaps it's returning the union of eids instead?

**To Reproduce**
```
from oneibl import one
one = one.ONE()

subjects = ['DY_003', 'DY_006']
assert one.search(subjects=subjects[0])  # pass
assert one.search(subjects=subjects[1])  # pass
assert one.search(subjects=subjects)  # fail
```

**Expected behavior**
the below lines should return the same output
```
eids = one.search(subjects=['DY_003', 'DY_006'])
eids = one.search(subjects='DY_003') + one.search(subjects='DY_006')
```
An alternative would be to change the docstring to make this clear

**Additional context**
I'm on develop

**Comment by oliche** [comment]
Yes it's because the automatic filter is by default an `exact` lookup.
We can change the behaviour of the filter, but the intention was for this specific kind of issues, to recommend the use of generic filters.

In this case, that would be this:
`one.alyx.rest('sessions', 'list', django='subject__nickname__in,["DY_003", "DY_006"]')`
