### ISSUE TITLE
Confusing Documentation For Installing IBLLIB

### ISSUE THREAD

**Issue by RylanSchaeffer** [int-brain-lab/ibllib#172]
This page (https://docs.internationalbrainlab.org/en/latest/02_installation_python.html) on how to install IBLLIB starts with:

"Before you begin, make sure you have installed ibllib properly on your system as per the previous instructions. Make sure your computer is connected to an IBL accredited network."

![image](https://user-images.githubusercontent.com/8942987/85161072-1767f380-b214-11ea-9486-de7bf1672d96.png)

This is quite confusing to me. I'm supposed to have ibllib installed before installing it, in accordance with unknown previous "previous instruction"?

**Comment by RylanSchaeffer** [comment]
https://docs.internationalbrainlab.org/en/latest/02_installation_python.html#initialisation

```
cd ibllib/
virtualenv iblenv --python=python3.7
source ./venv/bin/activate
pip install ibllib
```

This bit has a few questionable components.

1) It assumes that the directory ibllib has already been created.

2) I think `virtualenv` is Python2 syntax. I think the Python3 preferred approach is `python3 -m venv /path/to/new/virtual/environment`

3) The source command `source ./venv/bin/activate` might be wrong. It should be `source bin/activate`

**Comment by RylanSchaeffer** [comment]
Also, the instruction "The connections settings are defined in a JSON parameter file (named .one_params).

    In Linux, the file is in ~/.one_params.

"

doesn't appear to be true. I have no such file in my home directory.

**Comment by Alessandro2019-hash** [comment]
> This page (https://docs.internationalbrainlab.org/en/latest/02_installation_python.html) on how to install IBLLIB starts with:
> 
> "Before you begin, make sure you have installed ibllib properly on your system as per the previous instructions. Make sure your computer is connected to an IBL accredited network."
> 
> ![image](https://user-images.githubusercontent.com/8942987/85161072-1767f380-b214-11ea-9486-de7bf1672d96.png)
> 
> This is quite confusing to me. I'm supposed to have ibllib installed before installing it, in accordance with unknown previous "previous instruction"?

So here the wording is wrong, it should be "as per the following instructions" since you have done nothing before. I was also confused by this, but just keep reading.  I worked with Leenoy on this., and we created a directory  an empty directory _ibllib_, and kept going with the instructions below. 

I am using conda, and the comand we used was: 
### 
conda env create --name ibllib -f ibllib_conda.yaml
pip install ibllib

**Comment by oliche** [comment]
Thanks for your feedback.

We are moving to use a single environment for many IBL apps (https://github.com/int-brain-lab/iblenv) so that those steps are not necessary anymore and described in more details on the iblenv repository.

I have updated the documentation here:
https://docs.internationalbrainlab.org/en/latest/02_installation_python.html

It's quite hard for me to write documentation, since I'm very close to the project, many things seem obvious from my point of view while they are not. 
If you wish, you can edit the documentation here:https://github.com/int-brain-lab/ibllib/blob/develop/docs/02_installation_python.md and create a pull request, we will happily merge it !

Thanks !
