### ISSUE TITLE
datasets: camera.dlc, audiospectogram.times_mic not in the expected format 

### ISSUE THREAD

**Issue by Saksham20** [int-brain-lab/ibllib#208]
1. **camera.dlc**:
 expected shape `(nframes, npoints, 3`) based on this [google doc](https://docs.google.com/spreadsheets/d/1ieLXRPLLSgUKcLvFkrqizfZl5HjdfE6bQ2KLBCRmjQo/edit#gid=1097679410)
but currently retrieving it using one api:

```python
eid_camera='dfd8e7df-dc51-4589-b6ca-7baccfeb94b4'
camera_dlc = one.load(eid_camera,dataset_types=['camera.dlc'])
```
`camera_dlc` is a `list`, half of which contains datasets for body/right and left camera (.npy) files and remaining half contains dict with colnames information.  
There are some other eids for which it also returns files in `.pqt` format.

2. **audiospectrogram.times_mic**: 
```python
eid_raw_behavior='383f300e-ff4e-479a-8967-a33ea51b436e'
audio_spec_times = one.load(eid_raw_behavior,dataset_types=['_iblmic_audioSpectrogram.times_mic'])
```
returns a list of length 2, each are numpy arrays of timestamps. 
Expected: one np array.

**version**:
ibllib==1.5.11

**Comment by oliche** [comment]
related to #178 - I'm going to close this issue

Since the query is made on the dataset types, there could be several files in the output.
We are designing an user interface able to query individual files, in the meantime this will give you a more stable behaviour:

`files = one.load(eid_raw_behavior, dataset_types=['_iblmic_audioSpectrogram.times_mic'], download_only=True)`

```
Out[11]: 
[PosixPath('/datadisk/FlatIron/mrsicflogellab/Subjects/SWC_030/2020-07-30/001/raw_behavior_data/_iblmic_audioSpectrogram.times_mic.npy'),
 PosixPath('/datadisk/FlatIron/mrsicflogellab/Subjects/SWC_030/2020-07-30/001/raw_behavior_data/_iblmic_audioSpectrogram.times.npy')]
```
