### ISSUE TITLE
copyScript

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/ibllib#451]
Latest ibllib@copyScript

```bash
(iblenv) PS>cd C:\ibllib
(iblenv) PS>git status
On branch copyScript
Your branch is up to date with 'origin/copyScript'.

nothing to commit, working tree clean
(iblenv) PS>git fetch
(iblenv) PS>git status
On branch copyScript
Your branch is up to date with 'origin/copyScript'.

nothing to commit, working tree clean
(iblenv) PS>
```

Same issue with the copyScript if rename you rename a session, i.e. it moves the session inside the session that is to be overwritten/renamed. 
Right file browser: session that was going to be renamed
Left file browser: Server side mouse/day folder
Powershell Anaconda prompt: stuck at copying another session (looks like the normal transfer when ther is no renaming needed works jsut fine.)

![image](https://user-images.githubusercontent.com/7206665/157038844-93774b3b-3832-4649-8115-3dede4348fd6.png)

After waiting for the non renaming transfer to be completed:
```bash
All files copied
Traceback (most recent call last):
  File ".\transfer_video_session.py", line 24, in <module>
    confirm_video_remote_folder(local_folder=args.local, remote_folder=args.remote, force=args.force)
  File "c:\ibllib\ibllib\pipes\misc.py", line 365, in confirm_video_remote_folder
    flag_file.unlink()
  File "C:\Users\IBLvideo\Anaconda3\envs\iblenv\lib\pathlib.py", line 1309, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\iblrig_data\\Subjects\\ZFM-03324\\2022-02-24\\001\\transfer_me.flag'
(iblenv) PS>
(iblenv) PS>
```

**Comment by k1o0** [comment]
Hi Nicco, there's not really anything I can do from here.  You and @micheleangelofabbri will have to figure out what the problem is.  Some notes:

* The unit tests pass on my computer.  Try running the unit tests at the rig.
* I use your function to rename the folder.  The two paths printed to the command line are the ones passed to `shutil.move`.
* Check that the session folders aren't nested before running the copy.
* Set logging level to debug

rename_session:
https://github.com/int-brain-lab/ibllib/blob/50166d337b4ce365bf473551d5d1c87da3111ddf/ibllib/pipes/misc.py#L123-L127

confirm_video_remote_folder:
https://github.com/int-brain-lab/ibllib/blob/50166d337b4ce365bf473551d5d1c87da3111ddf/ibllib/pipes/misc.py#L341-L345
NB: the `remote_folder` variable is printed after 'REMOTE:'

https://github.com/int-brain-lab/ibllib/blob/50166d337b4ce365bf473551d5d1c87da3111ddf/ibllib/pipes/misc.py#L359

transfer_folder:
https://github.com/int-brain-lab/ibllib/blob/50166d337b4ce365bf473551d5d1c87da3111ddf/ibllib/pipes/misc.py#L139-L140

**Comment by micheleangelofabbri** [comment]
spinnakerSDK and python packages v2.7.0.128 now running on CCU ephys videoPC with python v3.8 by utilizing the following software:
* [Latest Python Spinnaker](https://flir.app.boxcn.net/v/SpinnakerSDK/folder/73501875299)
* [Latest Spinnaker Full SDK](https://flir.app.boxcn.net/v/SpinnakerSDK/folder/73503062578)

rsync/copyScript branch has been integrated into ibllib and iblscripts
