### ISSUE TITLE
Specify download location for `BrainAtlas` objects

### ISSUE THREAD

**Issue by jsiegle** [int-brain-lab/ibllib#548]
If I initialize a `ibllib.atlas` object (e.g., `AllenAtlas()`) after setting up ONE with a custom cache directory, the volume file is still downloaded to the default location.

I tried manually setting the ONE parameters using the following code, but this didn't seem to change anything with respect to the `AllenAtlas` class:
```python
import one.params as params
par = params.get()
par.set('CACHE_DIR', '/scratch')
params.save(par, 'https://openalyx.internationalbrainlab.org')
```

Is there currently a way to ensure `BrainAtlas` objects are cached in a custom location? If not, can this ability be added?

**Comment by seankmartin** [comment]
I had a similar issue @jsiegle, I solved it in a kind of hacky way. Posting in case it helps!

For me, I was able to set the directory that `AllenAtlas` downloaded data to via the following:

```
from pathlib import Path
import one

custom_cache_path = "your_custom_location"
param_file_location = one.params.iopar.getfile(one.params._PAR_ID_STR)
p = Path(param_file_location) / ".caches"
p.unlink(missing_ok=True)
one.params.CACHE_DIR_DEFAULT = custom_cache_path
one.params.setup(silent=True)
```

Then, the allen atlas would download to `custom_cache_path\openalyx.internationalbrainlab.org\histology\ATLAS\Needles\Allen`

Of course, this does delete the IBL parameter file, which was fine in my case - I only needed the cache directory. You might need to write over the information in the IBL parameter file otherwise.

**Comment by k1o0** [comment]
Hello, here's the proposed change: I've made the default relative path of the atlas a class attribute and the hist_path constructor argument may now be a directory path.  With this change you can (down)load the atlas with a non-default ONE instance by doing the following:
```
one = ONE(cache_dir='path/to/cache_dir')  # some none-default instance of ONE
target_path = one.cache_dir / AllenAtlas.atlas_rel_path
ba = AllenAtlas(hist_path=target_path)
```

How does this sound?

**Comment by jsiegle** [comment]
That sounds good!
