### ISSUE TITLE
NP course: iblsort + viewephys assignment & presentation

### ISSUE THREAD

**Issue by mayofaulkner** [int-brain-lab/ibllib#828]
- [x] raw data quality and viewephys presentation @oliche 
- [x] IBL sort presentation @oliche 

Due mid Sept:
- [x] IBL sort assignment @oliche 
- [x] viewephys assignment @GaelleChapuis 

NP course shedule https://docs.google.com/document/d/1Zz1Nx49atBPMMDLylmbSBxyl5GXq5om6G-yMRYZP7vQ/edit

**Comment by GaelleChapuis** [comment]
viewephys assignment: https://github.com/int-brain-lab/neuropixels_course_2024/tree/8e72afde70f28ba3d32abf5a8e544d50f350789a/viewephys

Notes:
- did not show the viewephys command that is nice when wanting to look at the data on disk, because adding the spikes to it would require changing the GUI to account for jumping across windows
- attempted the residual analysis on the raw data snippet using spike interface functions
```
import spikeinterface.extractors as se
import spikeinterface.generation as ge

# The inject_templates requires a Sorting object and a BaseRecording object.

# --- Option 1: Create Sorting object using just the spikes within the raw data snippet
sorting_obj = spikeinterface.core.NumpySorting(
    spikes=ssa, sampling_frequency=sr_ap.fs, unit_ids=su)
# This was bugging, although the input were as specified in the doc (simple numpy arrays)

# --- Option 2: Create sorting object using the reader
re = se.read_ibl_recording(one=one, pid=pid, stream_name=f'{probe}.ap')
# This however loaded the whole train of spike, and it was unclear how to restrict it to only the raw data snippet time

# The convolution function is the following, however it was unclear how to precise the length of it without a BaseRecording object
convolved_templ = ge.inject_templates(sorting=re, templates=negative_wavs)

```

**Comment by oliche** [comment]
Presentations : https://drive.google.com/drive/folders/1spCoSigx_umoNa1NzjD_CLN4U5HbOzKW
Code for courses: https://github.com/int-brain-lab/neuropixels_course_2024
