### ISSUE TITLE
processing.py has a pandas dependence - is that actually required?

### ISSUE THREAD

**Issue by kdharris101** [int-brain-lab/ibllib#84]

**Comment by berkgercek** [comment]
Just noticed this;

I added an optional behavior as part of playing around with using intervals instead of single timestamps for the `times` column of `TimeSeries` objects produced by `bin_spikes`. I can remove  the behavior as it is the only pandas dependency we have at the moment, and isn't used unless the user explicitly requests intervals as the indices instead of bin left edges.
