### ISSUE TITLE
Remove 'peakVelocity_times' from QC trials table

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ibllib#853]
Peak velocity times are per wheel movement, not per trial and should therefore be removed from the QC trials table.

**Comment by bimac** [comment]
This wasn't the root cause ...

The truncation of `peakVelocity_times` to the number of trials (which causes it to be displayed in the trials table) happens during syncing of timestamps between bpod and fpga: see [ephys_fpga.py#L945-L948](https://github.com/int-brain-lab/ibllib/blob/bbf915ddd937c506c6ac0e597fcebe5ff72891b9/ibllib/io/extractors/ephys_fpga.py#L945-L948).

**Comment by bimac** [comment]
4cb2ee3a resolves `peakVelocity_times` showing up in the trials table, should I open a separate issue for the truncation?
