### ISSUE TITLE
MesoscopePreprocess tasks erroring

### ISSUE THREAD

**Issue by samupicard** [int-brain-lab/ibllib#883]
A number of MesoscopePreprocess tasks are erroring for unclear reasons. 

The error seems to be related to the way badframes are being concatenated across imaging bouts. The error message thrown:

```
2024-11-15 01:06:00,791,791 ERROR [tasks.py:267] Traceback (most recent call last):
File "/home/ibladmin/Documents/PYTHON/envs/suite2p/lib/python3.10/site-packages/ibllib/pipes/tasks.py", line 257, in run
outputs = self._run(**kwargs)
File "/home/ibladmin/Documents/PYTHON/envs/suite2p/lib/python3.10/site-packages/ibllib/pipes/mesoscope_tasks.py", line 800, in _run
badframes = np.r_[badframes, raw_mat + total_frames]
OverflowError: Python integer 13389 out of bounds for uint8
```

Example sessions that are erroring like this:
- MesoscopePreprocess 3408a651-41f9-402c-ad1d-f147f7cca9ee SP061/2024-11-05/001
- MesoscopePreprocess 3a35cb25-1e58-42db-b3f1-d6aa56f0cfd9 SP061/2024-11-07/001
- MesoscopePreprocess 00fbcc3f-9ee1-4993-9f94-ce8be232752c SP061/2024-11-08/001
- MesoscopePreprocess af8ea8be-b9b2-474b-9302-e9e449b5e2d6 SP061/2024-11-12/001
- MesoscopePreprocess 7ba8c055-a1a8-4cf9-9acf-1c43f2a99dbf SP061/2024-11-13/001

**Comment by k1o0** [comment]
For some reason the dtype for bad frames was set absurdly low. When I refactored this part a few months ago I carelessly kept the type without thinking much of it. Sorry about that. I think this error appeared because Numpy 2.0 no longer 'upcasts' array types.
https://github.com/int-brain-lab/ibllib/blob/e110a244db60f67cd47d1e01c10a8faec132885c/ibllib/pipes/mesoscope_tasks.py#L793
I will change this to uint32 which at 10Hz will give you 119,304 hours of bad frame numbers.
